### ISSUE TITLE
rewrite `org-dotemacs-load-blocks' to use `org-babel-map-src' [$100]

### ISSUE THREAD

**Issue by vapniks** [vapniks/org-dotemacs#5]
Use `org-babel-map-src` and `topological-sort` in `org-dotemacs-load-blocks` and remove `org-dotemacs-extract-subtrees`. I have written comments with more details in the code file (above `org-dotemacs-load-blocks`).

**Comment by zhouchongzxc** [comment]
may I have some org-dotemacs.org files for test ?

email : 297188259@qq.com

**Comment by vapniks** [comment]
I have added a file dotemacs-test.org to the repository.
Please have a look at the comments I have made in that file, and also the comments in org-dotemacs.el above `org-dotemacs-load-blocks' and `org-dotemacs-extract-subtrees'.

**Comment by zhouchongzxc** [comment]
as  you mentioned "It should also report any cycles in the dependency graph"

i had write a function to do that .  in the file of scratch.el

but it need more test

**Comment by vapniks** [comment]
I think the `topological-sort` function can do this already.

**Comment by zhouchongzxc** [comment]
I add another function to do that ,
It may be helpful

**Comment by zhouchongzxc** [comment]
" loop over the code blocks using `org-babel-map-src-blocks' storing them in some 
variable and then use `topological-sort' to load the block in the right order "

I have edited the dotemacs-test.org for test. and the .el file.

test with (org-dotemacs-load-blocks-1 "dotemacs-test.org" "tag1")

**Comment by zhouchongzxc** [comment]
new function    org-dot-emacs-load

**Comment by vapniks** [comment]
can you make a pull request so I can see what you have done?

**Comment by zhouchongzxc** [comment]
there are something to be done. I will show you the result when I finish it.

**Comment by zhouchongzxc** [comment]
I think the variable `org-dotemacs-exclude-todo' is not necessary.                                                                                            
                                                                                                                                                              
because when block-5 is "broken",but block-1 depend on block-5,and                                                                                            
                                                                                                                                                              
block-1 must be evaluated, what would happen?                                                                                                                 
                                                                                                                                                              
also the variable `org-dotemacs-error-handling'. you had said that                                                                                            

" It should also report any cycles in the dependency graph, and maybe work out missing dependencies                                                           
if possible (i.e. blocks that don't load should be tried again after loading more blocks, and then                                                            
these blocks can be reported as dependencies for the block that didn't load initially)"   
                                                                    
so ,it retry always, no skip.

**Comment by zhouchongzxc** [comment]
I am sorry .I decide to give up this item.

but I will write code for it..

**Comment by vapniks** [comment]
Sorry I have been slow to respond to your comments. I just tried ```org-dotemacs-load-blocks-1``` and it seems to work fine so far, thankyou. It should ignore "BROKEN" blocks and treat them as though they do not exist, so that any blocks depending on broken blocks are not evaluated. The thing I said about tryi
